### ISSUE TITLE
Blog posts appear to render without CSS

### ISSUE THREAD

**Issue by dotsdl** [datreant/datreant.github.io#3]
The [blog](http://datreant.org/blog/) currently seems to render without any CSS. I'm not in a position to troubleshoot this at the moment, so any help from Jekyll/Hyde users appreciated.

**Comment by orbeckst** [comment]
See comment on PR #1 – basically make the URL for the CSS absolute:
```
_includes/head.html:  <link rel="stylesheet" href="{{ site.baseurl }}/public/css/poole.css">
```

**Comment by orbeckst** [comment]
Actually, you already had it as
```
_includes/head.html:  <link rel="stylesheet" href="{{ site.baseurl }}public/css/poole.css">
```
but without the `/`. Either add `/` or make sure that `site.baseurl: /` is set.

**Comment by orbeckst** [comment]
Weirdly enough, you already have
```yaml
baseurl:          /
```
in `_config.yml`. 

Not sure why the `/` is not properly included. This might be something that Jekyll does in order to be smart.

**Comment by orbeckst** [comment]
For the MDAnalysis site we left `baseurl` empty and use `{{ site.baseurl }}/` with explicit trailing slash *everywhere* https://github.com/MDAnalysis/MDAnalysis.github.io/issues/16#issuecomment-385572553 (the comment has more background info).
